import localFont from "next/font/local";
import { headers } from "next/headers";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fsAlbertArabic = localFont({
    src: [
      {
        path: "../fonts/FSAlbertArabic/FSAlbertArabic-Light.ttf",
        weight: "300",
        style: "normal",
      },
      {
        path: "../fonts/FSAlbertArabic/FSAlbertArabic-Regular.ttf",
        weight: "400",
        style: "normal",
      },
      {
        path: "../fonts/FSAlbertArabic/FSAlbertArabic-Thin.ttf",
        weight: "500",
        style: "normal",
      },
      {
        path: "../fonts/FSAlbertArabic/FSAlbertArabic-Bold.ttf",
        weight: "700",
        style: "normal",
      },
    ],
    variable: "--font-fs-albert-arabic",
    display: "swap",
  });

export default async function RootLayout({ children }) {
  // Next 16: request APIs async
  const h = await headers();

  // next-intl middleware sets this header
  const locale = h.get("x-next-intl-locale") || "ar";
  const dir = locale === "ar" ? "rtl" : "ltr";

  

  return (
    <html lang={locale} dir={dir}>
      <body className={`${fsAlbertArabic.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
